### PR TITLE
#50 | John | Allow for Reset

### LINKED ISSUE #50: Make System Default State [FE]
## Task Information
Enable resetting the system to a default state (an empty registry with the default user)

### LINKED ISSUE #65: Make Default User [FE]
## **Feature Information**
Make a default user for both the initial and "Reset" state
- This user should be an admin and have use the given user/pass

> - **Username:** ece30861defaultadminuser
> -  **Password:** correcthorsebatterystaple123(!__+@**(A;DROP TABLE packages

**Notes**
-(Consider why this password looks so strange, and make sure you handle
user input carefully.)

### PR DESCRIPTION
**Pull request by j-leidy**
closes #50

### CODE REVIEW

**Comment by BellJrDev** [comment]
Ok so I see that you have made some nice additions to the codebase. With this particular task, I think I confused myself a little with the scoping (between BE and FE, who does the heavy lifting?). I was thinking FE would be doing the heavy lifting, but I now that I think about it, it does make sense for the BE to do that. 

If I am correct in believing that you approached the task as "frontend sends req, backed makes the req work", then I think this feature can be marked as complete and merged. Please let me know.  @j-leidy

**Comment by j-leidy** [comment]
Yes the logic behind removing things from the DBs etc should be handled by the Backend.

**Comment by BellJrDev** [comment]
Yes sir. Understood. Submitting my approval now.

**Review by BellJrDev — APPROVED** [review]
Successfully added option to reset! You're good to go

**Pull request merged**
