### PR TITLE
Completed version dependence (Again)

### LINKED ISSUE #39: Score Version Dependence [BE only]
## Task Information
Score Version Dependence

The VersionDependence score comes from the following: 
The fraction of dependencies that are pinned to at least a specific major+minor version
- A package with 0 dependencies gets a score of 1
- A package with 2 dependencies, one of which is constrained to a minor+major version (eg 2.3.X) gets a ½ = 0.5 score
  
**Notes**
- You are responsible for interfacing with the ModEval Provider which wrapped over the inherited code from Octavo. Ensure that your solution is encapsulated and flows with the rest of the ModEval smoothly, not breaking anything or otherwise upsetting the subsystem. ModEval is already fitted with some space and configuration settings for your addition

### PR DESCRIPTION
**Pull request by bkanter-purdue**
Ignore the branch name, had completed version dependence then moved to a new branch, then had to redo version dependence. 
Calculates using this basic idea:
`
if (number_of_dependencies == undefined)
    {
        return 1;
    }
    return 1 / (1 + (number_of_dependencies/2));
`
Tested the undefined case.

### CODE REVIEW

**Review by BellJrDev — CHANGES_REQUESTED** [review]
Please update your branch with dev

**Review by BellJrDev — CHANGES_REQUESTED** [review]
VersionDependence.spec.test is succeeding for any tests contained in it. But RequestTests.spec.ts has a failure for GetPackageWithID. Please resolve!

**Comment by bkanter-purdue** [comment]
@BellDorian 
Made requested change

**Review by BellJrDev — APPROVED** [review]

**Comment by BellJrDev** [comment]
Excellent work with this one, Ben. You're good to merge!

**Pull request merged**
